name: elapor_mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  image: ^4.0.17
  permission_handler: ^11.4.4
  uuid: ^4.0.0
  geocoding: ^2.1.1
  file_picker: ^5.3.1
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
